### ISSUE TITLE
TERM_MAPPING in BMM has no ancestors

### ISSUE THREAD

**Issue by serefarikan** [openEHR/reference-models#4]
@wolandscat  Should not the definition of TERM_MAPPING in basic types bmm file have any as its ancestor?

**Comment by wolandscat** [comment]
All class definitions in a BMM file with no stated ancestors are given the ancestor Any by default. So the query 'ancestors' for any class in the loaded schema will always result in at least one class.

**Comment by serefarikan** [comment]
@wolandscat  That is what I assumed, but all other types I've seen so far seem to have their ancestors set to <"Any", ...> explicitly. That's the reason I opened the issue

**Comment by wolandscat** [comment]
That's probably true - I should perform a clean-up on the schemas...
